#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION "2020.1.0a21"
#define UNITY_VERSION_DIGITS "2020.1.0"
#define UNITY_VERSION_SUFFIX "a21"
#define UNITY_VERSION_VER 2020
#define UNITY_VERSION_MAJ 1
#define UNITY_VERSION_MIN 0
#define UNITY_IS_BETA 1
